import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { serverEnvConfig } from "@/config/server-env.config";
import AppProvider from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const isPro = serverEnvConfig.app.isPro;
const appName = serverEnvConfig.app.name;
const env = serverEnvConfig.app.env;
const appTitle = isPro ? appName : `${appName} - ${env}`;

export const metadata: Metadata = {
  title: appTitle,
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full">
        <AppProvider className="min-h-screen">
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
